name: signapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: any
  camera_windows: any
  http: ^1.1.0
  image: any

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/



# Add this section to fix the build error
dependency_overrides:
  win32: ^5.0.0
  ffi: ^2.1.0
  tflite_flutter: ^0.11.0
